FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN apt-get update && apt-get install libgl1-mesa-glx ffmpeg libsm6 libxext6 -y
RUN pip install --no-cache-dir -r requirements.txt

COPY api/ ./api/
COPY vit/ ./vit/
COPY llm/ ./llm/
COPY rag/ ./rag/

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
